import { C } from './constants'

export const ss = {
  container: {
    maxWidth: 480,
    margin: '0 auto',
    minHeight: '100vh',
    position: 'relative',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    border: `1.5px solid ${C.soft}`,
    borderRadius: 12,
    fontSize: 15,
    fontFamily: 'Outfit, sans-serif',
    background: C.soft,
    color: C.ink,
    transition: 'all .2s',
  },
  select: {
    width: '100%',
    padding: '12px 16px',
    border: `1.5px solid ${C.soft}`,
    borderRadius: 12,
    fontSize: 15,
    fontFamily: 'Outfit, sans-serif',
    background: C.soft,
    color: C.ink,
    appearance: 'none',
    cursor: 'pointer',
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    border: `1.5px solid ${C.soft}`,
    borderRadius: 12,
    fontSize: 15,
    fontFamily: 'Outfit, sans-serif',
    background: C.soft,
    color: C.ink,
    resize: 'vertical',
    minHeight: 90,
    transition: 'all .2s',
  },
  card: {
    background: '#fff',
    borderRadius: 16,
    padding: 20,
    boxShadow: '0 2px 12px rgba(0,0,0,.06)',
    marginBottom: 14,
  },
  label: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '1.2px',
    color: C.muted,
    marginBottom: 6,
    display: 'block',
  },
}
